version: '3.7'
services:
  python_api:
    build: ./python_api
    container_name: python_api
    restart: unless-stopped
    volumes:
      - ./python_api:/python_api
    env_file:
      - ./python_api/app/.env
    environment:
      - APP_NAME=predict_API
    
    # Connects to nginx via nginx.conf
    expose:
      - 8080
  
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    restart: unless-stopped
    # Redirect all request to https
    ports:
      - "80:80"
      - "443:443"
    # Tell nginx where the certificates are docker folder : nginx folder
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt # for letsencrypt validation challenge
      - ./data/certbot/www:/var/www/certbot # for the actual certificates
    depends_on:
      - python_api
    # Reload the every 12 h updated certificates
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    # Tell certbot where the conf and www folder is
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    # Renew the every 12h obtained certificates
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  python_api:
